tika/tika.py

Hi @chrismattmann  pulled request. So, you can test it......

Tika rest for testing

---

tika/tika.py

Hi, @chrismattmann changed for remote files.

fixed for remote file

---

README.md

Hi, @chrismattmann this needs requests module installed.

need requests module

---

README.md

Reverts chrismattmann/tika-python#22

Revert "need requests module"

---

README.md
tika/tika.py

Hi, @chrismattmann added it. Try it.

 deleted useless comments and added port checking in parser/detector/config

---

tika/tika.py

Hi, @chrismattmann Try this one. I've changed it to callServer function. 
Related to #23

changed for port checking in callServer

---

tika/tika.py

* write log in tika-server.log
This set of revisions were originally in
a80f419bd7ec69c8dbac76d6329989527eb8e87f and have been rebased.

fix for shell dependency

---

tika/tika.py

This helps when you want to write response, with special characters, into a file.

Added comment to encode response in UTF-8

---

tika/tika.py

Upgrade to Tika 1.12

---

README.md
tika/config.py
tika/detector.py
tika/language.py
tika/parser.py
tika/tests/tests.py
tika/tests/tests_params.py
tika/tika.py
tika/translate.py

Just continued on from what @Pehat started here: 422cd3feb109f93b6d3b5c6a1d1789bb608c8678

Continuing with python3 support

---

README.md
setup.py
tika/config.py
tika/detector.py
tika/language.py
tika/parser.py
tika/tika.py
tika/translate.py

Hi, Chris. I've made some very simple changes in order to run your binding on both Python 2 and Python 3. Please consider merging it into master.

Basic Python3 adaptation is performed

---

tika/tika.py

@chrismattmann 
This trivial PR removes extraneous debug/sanity print statement, already present in Readme.
Thanks!

fix for #91

---

tika/tika.py

Reverts chrismattmann/tika-python#93

Revert "Added using virtual environment variables"

---

README.md
tika/tika.py

This closes #95, trying to trigger Travis to test again.

Adding env vars support from #93 to address #95

---

tika/tika.py

Added a variable to allow the log file for the Tika server to be
different to that of the Jar file path. This is valuable when changing
the TikaJarPath as well. In my case I am putting the Jar file in a
permanent location other than /tmp, but I want the log file to be in
/var/log/ where it can be rotated automatically.
Fixed a duplicate import and some spacing.

Add the ability to change the Tika Server's log file path

---

tika/tika.py

When `tika-python` is imported, there aren't log messages, so I added [standard Python logger](https://docs.python.org/2/library/logging.html) to manage file and stdout.
I replaced `die` function with `raise`, so I can catch these exceptions.
When imported `tika-python`, now, will log in root logger.

Added logger for file and stdout

---

tika/tests/arguments/test_remote_content.csv
tika/tests/arguments/test_remote_metadata.csv
tika/tests/arguments/test_unsupported.csv
tika/tika.py
tika/unpack.py

Integrate Unpack interface to use /unpack/all #119

Integrate Unpack interface to use /unpack/all #119

---

tika/detector.py
tika/language.py
tika/parser.py
tika/tika.py
tika/translate.py

Using reST documentation template for doc strings.
Closes #136 
Some of the parameters are undocumented, they assume a default values, maybe we can revisit in second pass to document those missing parameters.

Added documentation to methods

---

tika/tika.py

This PR addresses issue #140 and removes the hardcoded scheme `http`. This way - if the original scheme was e.g. `https` then this will be kept (instead of overwriting it with `http`).
Please be aware that this PR currently hardcodes `verify=False` which means that the SSL/TLS connection is not checked (e.g. for hostname match/CA trust). This might not be appropriate it a few/most cases.

enable https scheme

---

tika/__init__.py
tika/tests/test_tika.py
tika/tika.py

Upgrade to 1.15

---

README.md

as per request on [#131](https://github.com/chrismattmann/tika-python/issues/131)

added readme notes on how to output xhtml from the parser. 

---

tika/tests/tests_unpack.py
tika/unpack.py

This fix will solve the problem of using the unpack interface on unicode texts.

Fix the utf-8 issue on the unpack interface

---

README.md
tika/detector.py
tika/language.py
tika/parser.py
tika/tika.py
tika/translate.py
tika/unpack.py

Closes #217. Instead of just adding a timeout I added the ability to pass any additional params to the requests call in case others might be required.

Add requestOptions to customize Tika server request

---

README.md

Thanks for merging #232! Was just looking over my changes and realized a link must have gone dead - fixing it here.

Fix requests docs dead link

---

README.md

As requested, see issue https://github.com/chrismattmann/tika-python/issues/238

added documentation for airgap setup

---

tika/tika.py

I noticed that #222 was not fully fixed.

fix bug: Further bug fix #222

---

tika/parser.py
tika/tests/files/rwservlet.pdf
tika/tests/test_tika.py
tika/tika.py

Closes https://github.com/chrismattmann/tika-python/pull/240/files

Allow parsing from binary streams

---

tika/tika.py

This should fix the error reported in #256. 
While not an actual fix to the exception, I don't think there's much we can do if the system failed to find our previously created process.

fix ocasional OSError

---

.gitignore
tika/unpack.py

Fixes https://github.com/chrismattmann/tika-python/issues/287

Fix "_csv.Error: line contains NUL"

---

tika/unpack.py

I'm trying to reduce the memory usage in unpack. 
Changes:
-  all files usages now use a `with`  block, in order to make sure files are closed and possibly avoid memory leaks.

unpack: use with blocks when handling files

---

.travis.yml
README.md
setup.py
tika/__init__.py
tika/tests/memory_benchmark.py
tika/tests/test_benchmark.py
tika/tests/test_tika.py
tika/tests/utils.py
tika/tika.py

Closes https://github.com/chrismattmann/tika-python/issues/305
Bump Tika to 1.24.1
Add tests for benchmarking gzip compression

Tika 1.24.1 - gzip (de)compression

---

tika/unpack.py

This pull request enables headers specification in `unpack.from_file`.

Allow for headers in unpack.from_file
