chrismattmann/tika-python

- .gitignore
- README.md
- setup.py
- tika/parser.py
When running Tika in a Docker linked container (for example, within `docker-compose` linking), it's important to have an ability to pass Tika's container URL along with a programatically invocation. Also it's useful when running Tika on multiple instances.
Now it's possible with optional:
```python
parsed = parser.from_file('/path/to/file', 'http://tika:9998/tika')
string_parsed = parser.from_buffer('Good evening, Dave', 'http://tika:9998/tika')
```
README updated, version bumped, minor styling fixes (EOL, trailing spaces)
> parser.py: add serverEndpoint as optional param

- tika/parser.py
Hey Chris,
Currently the metadata object gathered from parsing a document has an extra nest of lists for every key.
Shortened Example:
```
{
u'access_permission:can_modify': [u'true'], 
u'access_permission:extract_content': [u'true'],  
u'X-Parsed-By': [[u'org.apache.tika.parser.DefaultParser', u'org.apache.tika.parser.pdf.PDFParser']]
}
```
This deviates from the result that you get when you call Tika from the command line:
```
{
"access_permission:can_modify":"true",
"access_permission:extract_content":"true",
"X-Parsed-By":["org.apache.tika.parser.DefaultParser","org.apache.tika.parser.pdf.PDFParser"]
}
```
Not sure if that nesting is there for a reason, so feel free to ignore if so.
> Remove extra list nesting in metadata hash map

- tika/tika.py
Currently ```--server``` points to ServerEndPoint which is not passed to the ```runCommand``` method and thus lead us nowhere. 
Hence, modified ```--server``` reference to ```serverHost``` and passed it to the ```runCommand``` method. For eg: To parse image data using Tika Server, we can use the below command:
```tika.py --server localhost --port 9990 parse all /tmp/xyz.jpg```
> Modified --server reference to serverHost

- tika/tika.py
Fixes to make the command line tika-python parse function work again. Replace urlOrPaths with path iterator; make sure that we use codecs.open to open files if it's pre-Python3.
> Fixes to make the command line tika-python parse function work again

- README.md
- tika/tika.py
When running the detector from the CLI, it only outputs the detection results, e.g.:
```
image/jp2
image/jp2
image/jp2
image/jp2
```
This is consistent with the CLI of the Java version, but it is not very helpful when you're e.g. processing all files in a directory (because it makes it impossible to track to what file each result corresponds). 
This  patch adds a `-c` / `--csv` option, which allows one to report the detection results as a comma-separated list that includes the name (or full path, depending on how the tool is called). Here's an example:
python tika.py -c detect type ~/jpylyzer-test-files/*
Result:
```
/home/johan/jpylyzer-test-files/reference.jp2,image/jp2
/home/johan/jpylyzer-test-files/truncated_at_byte_5000.jp2,image/jp2 …
```
> Added switch that reports type detect results in CSV format  (including file names/paths)

- tika/__init__.py
@chrismattmann 
This trivial PR adds __version__ to __init__.py typical to most python libraries **[0]** 
```
>>> import tika
>>> 
>>> tika.__version__
'1.13.1'
```
The **version** variable found in **setup.py** is to fetch the latest tika-server.jar from Maven Central, while building tika-python.
[0] http://stackoverflow.com/a/20180564/5061477
> add versioning to tika-python library

- tika/tika.py
The log call didn't provide a format for the status code, resulting in an exception.
> Corrected log call when the Tika server returns an unexpected HTTP status

- README.md
- tika/tika.py
Without this patch, multiple instances of tika-python in client mode run by different unix users required write access to the same `/tmp/tika.log` file, which caused an error on import.
With this patch, the path for both the `tika-server.log` file and `tika.log` file is configurable through the `TIKA_LOG_PATH` environment variable.
This should close #133.
> Read the log file path from TIKA_LOG_PATH

- tika/tika.py
- tika/unpack.py
Add the ability to hit the Tika _/unpack/all_ interface which allows extracting metadata, text and attachments from one analysis run. Details are extracted in a dictionary as is done in _parser_.
Also change from using the root logger name to using _tika.tika_ to assist integration with other libraries.
> Unpack interface to use /unpack/all

- README.md
- tika/tika.py
I added this environment variable because I was having issues with the default save location for the Tika jar (/tmp). After restarting the computer, the file ofcourse disappears and there is a bug where this library tries to read `TikaJarPath` without properly checking if the file exists and throws an error which breaks my system. This happens inside `checkJarSig()` (I know this check is done before calling the function but it is compromised by the check for `urlp.scheme != ''`).
Rather than fixing this issue and introducing more bugs (since I did not have time to study the signficance of `urlp.scheme`), I just felt it is totally logical to have an environment variable to enable me to specify where the jar and md5 files are downloaded to (I want them in my application root directory) and …
> Add TIKA_PATH environment variable

- README.md
- tika/tika.py
As discussed in #113:
* Added `TIKA_JAVA` to env vars to support alternative javas
* Added `TIKA_STARTUP_SLEEP` to env vars to support customization of sleep
* Added `TIKA_STARTUP_MAX_RETRY` to env vars to support customization of retry/checks and avoid potential inf loop
* Add return status to `startServer` and check; throw `RuntimError` if failed
* Add error logs with description of issue
* Documented env vars in `README.md`
> PR re: issue #113

- tika/detector.py
- tika/parser.py
- tika/tika.py
I updated the tika server to version 1.19 and added options to the parsers and detectors to pass a custom configuration file. The default for the configuration file is None, so it should be backwards compatible. The changes have passed the tests in test_tika.py.
> updated to v1.19 and added custom config option

- tika/tests/test_ssl_link.py
@chrismattmann I've added test to check the url https://www.nasa.gov/sites/default/files/thumbnails/image/j2m-shareable.jpg on python 2.6. The test just uses the urlretrieve and does not use any pytika code.
As you can see, the test fails on 2.6.
> standalone test to check ssl issue

- tika/tika.py
tika.parser.from_file reports UnicodeEncodeError when called with non-ascii file name.
this commits fixes it.
please consider merging. -_-
>  fix bug: non-ascii file name not supported 

- README.md
- tika/tika.py
Hi, I open new PR, as it almost impossible to get rid of auto-format issues in previous. 
This PR adds a new environmental variable to control JVM options when starting Tika server
> New configuration property TIKA_JAVA_ARGS to adjust JVM options for Tika

- tika/tika.py
The new 1.22 release completely breaks any calls to callServer for me, I propose this change to fix it. Seems I am not the only one, see #252. 
A few comments on the change itself :
Removed the closing of a non existing file (introduced at #229)
I thought about moving it after the read but didn't because the callServer call get's the reader from the parent. Therefore, the parent should be responsible for closing it. If the caller needs to have the file opened less time it should manage the read itself and after that call callServer with bytes directly in my opinion.
> Remove closing on bytes

- tika/parser.py
- tika/tests/test_from_file_service.py
Expose service in the `from_file` parser functionality allowing content-only or metadata-only extraction strategies, useful when trying to implement more intrincated OCR strategies from tika.
Have not changed `from_buffer` since it invokes CallServer directly.
> expose service in the from_file parser

- README.md
- tika/tests/test_tika.py
- tika/tika.py
Allows us to kill the tika server and clean up some ram. Fixes #235
I still need to test if everything is working fine, so I'll leave this as a draft for now.
Another thing that I was thinking about was to automatically call this function when the program ends. I believe this could be achieved through [atexit](https://docs.python.org/3/library/atexit.html) ([source](https://stackoverflow.com/a/3850271/4542015)).
> Add killServer() function

- requirements.txt
The Travis build fails for Python 3.4 ([reference](https://travis-ci.org/chrismattmann/tika-python/jobs/636027154?utm_medium=notification&utm_source=github_status)) since the transitive dependency `pyyaml` from `python-coveralls` dropped support for EOL Python 3.4 in version `5.3` (released on Jan 6th).
```bash
PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.8
The command "pip install -r requirements.txt" failed and exited with 1 during.
```
This pull request pins `pyyaml` to the last version supporting Python 3.4 (`pyyaml:5.2`).
> Also see: https://github.com/yaml/pyyaml/commit/039c9eb3082de06063fa669cf41a73dbeabb5d84
> fix(): pyyaml dropped support for python 3.4

- tika/parser.py
- tika/tests/test_from_file_service.py
This PR resolves an issue where the documentation is not in accordance with the implementation of `parser.from_file`. 
* Changed parameter order of `parser.from_file` to match documentation examples
* Added a unit-test to test the behaviour
* Added documentation for `service` to `parser.from_file`
* Closes #273
> fix(parser): align `parser.from_file` with doc

- tika/tika.py
Checks for Windows on TikaServerProcess. If Windows, makes a different call.
os.setsid is only available in Unix:
https://stackoverflow.com/questions/38083168/attributeerror-module-os-has-no-attribute-setsid
Found an alternative command that seems compatible with Windows:
https://stackoverflow.com/questions/42257512/difference-between-subprocess-popen-preexec-fn-and-start-new-session-in-python
> Fix TikaServerProcess

- .travis.yml
- tika/tika.py
Previous patch failed on another Windows machine, particularly in Python 2. Since TravisCI does not support Python in Windows yet (and the linux tests work fine), these errors slipped past the TravisCI. I manually ran the test .py files that the TravisCI runs using a Windows machine that has all 4 versions of Python specified in the .travis.yml (2.7, 3.4, 3.5, 3.7).
Based on the TravisCI logs of the linux tests, these are the files run from tika\tests:
test_tika.py
test_from_file_service.py
test_ssl_link.py
All 12 tests (4 versions, 3 each) ran OK, but this certainly could use more testing on Windows.
> Revised patch from commit ea4ce60

- tika/tika.py
Tika fails to start when TIKA_PATH contains spaces. A common case would be applications storing the tika jar in `Application Support` on macOS – iscc-cli is an example for this:
https://github.com/iscc/iscc-cli/blob/ad466c3/iscc_cli/__init__.py#L8-L10
Tika server log will contain this (please excuse the german content, should be clear anyway):
Fehler: Hauptklasse Support.iscc-cli.tika-server.jar konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: Support.iscc-cli.tika-server.jar
The TIKA_PATH set by iscc-cli: `/Users/strayer/Library/Application Support/iscc-cli`
> Fix ClassNotFoundException with spaces in TIKA_PATH

- tika/tika.py
This is a followup to #307. I broke Windows with my change there, because single quotes can't be used in the command prompt as on Unix systems.
This is not ideal because `classpath` could be interpreted by the shell. Better would be to not run the command with `shell=True` at all and instead provide a list to `Popen` to let the subprocess module handle escaping of paths and such.
> Fix Windows breakage caused by #307

- README.md
Updated README.md "Airgap Setup", telling users:
1. To also download the .md5 file
2. The location of the Maven repo containing the files + md5 files.
Addresses issue #308
> Update README.md "Airgap Setup" Section

- tika/tika.py
Even after Tika server is started, the while body will keep being executed until max retries is reached. It should break out of the loop upon successful startup.
> Fix unnecessary retries after successful startup

- README.md
I wanted to use the library with a file that I get from another server, thus I already had the file in memory. It took me a while to understand how to hand it to tika without first having to write it to disk, party because there were no examples.
Counterintuitively, the `from_file` method does not work, since it relies on the `name` attribute of a [FileIO](https://docs.python.org/3/library/io.html#io.FileIO) object, which a file in memory (used with [BytesIO](https://docs.python.org/3/library/io.html#io.FileIO)) does not have. I don't think that the name is really necessary in the case of in-memory files, but that would be another issue to fix this.
The `from_buffer` method in always shown with strings and the parameter is always called "string" until it ends up in the `callServer` method …
> [documentation] Add example with byte buffer

- tika/unpack.py
It seems to me that the `headers=` argument was misplaced and was expected in `from_buffer` instead of `from_file`.
Thanks for your work on python-tika!
> fix unpack from_file/from_buffer headers arg

- .github/workflows/documentation.yml
- docs/Makefile
- docs/make.bat
- docs/source/conf.py
- docs/source/index.rst
- docs/source/modules.rst
- docs/source/readme.rst
- docs/source/setup.rst
- docs/source/tika.rst
- docs/source/tika.tests.rst
I propose adding automated documentation using github actions/pages to this package.
You are welcome to observe a working version from my fork here: https://aleksandrskrivickis.github.io/tika-python/tika.html
> Add automated documentation
